<template>
  <div class="tab-content">
    <section class="chart-card hero"><div><p class="eyebrow">FUTURES / DRY-RUN</p><h2>模拟交易控制台</h2><p class="muted">计划批准后由 Freqtrade dry-run 执行，止盈止损由策略管理。</p></div><div class="status" :class="statusAvailable ? 'online' : 'offline'"><span class="dot" />{{ statusAvailable ? 'Freqtrade 已连接' : 'Freqtrade 未连接' }}</div></section>
    <section class="chart-card"><div class="chart-header"><h3>账户</h3><button class="btn" @click="refresh">刷新</button></div><div v-if="snapshot.available" class="account-grid"><div><span>余额</span><b>{{ formatBalance(snapshot.balance) }}</b></div><div><span>当前持仓</span><b>{{ positions.length }}</b></div><div><span>模式</span><b>Futures / Isolated / Dry-run</b></div></div><p v-else class="muted">{{ snapshot.error || '等待 Freqtrade 服务' }}</p></section>
    <section class="chart-card"><div class="chart-header"><h3>当前模拟持仓</h3><span class="muted">每 15 秒同步</span></div><div v-if="positions.length" class="positions"><div v-for="position in positions" :key="position.id" class="position"><div class="position-head"><strong>{{ position.pair }}</strong><span :class="position.side">{{ position.side === 'long' ? '做多' : '做空' }}</span><span class="state">{{ statusLabel(position.status) }}</span></div><div class="metrics"><span>入场 <b>{{ position.actualEntryPrice || position.entryPrice }}</b></span><span>现价 <b>{{ position.currentRate || '--' }}</b></span><span>数量 <b>{{ position.amount || '--' }}</b></span><span>止损 <b>{{ position.stopLoss || position.stopPrice }}</b></span><span>浮盈亏 <b :class="(position.currentProfit || 0) >= 0 ? 'profit' : 'loss'">{{ formatPercent(position.currentProfit) }}</b></span><span>Trade ID <b>{{ position.tradeId || '--' }}</b></span></div></div></div><p v-else class="muted empty">暂无持仓。批准计划后，执行器会自动尝试开仓。</p></section>
    <section class="chart-card"><div class="chart-header"><h3>交易计划</h3></div><div v-if="plans.length" class="plans"><article v-for="plan in plans" :key="plan.id" class="plan" :class="plan.side"><div class="plan-top"><strong>{{ plan.pair }}</strong><span class="badge">{{ plan.side === 'long' ? '做多' : '做空' }}</span><span class="state">{{ statusLabel(plan.status) }}</span></div><div class="metrics"><span>入场 <b>{{ plan.entryPrice }}</b></span><span>止损 <b>{{ plan.stopPrice }}</b></span><span>TP1/TP2 <b>{{ plan.takeProfit1 }} / {{ plan.takeProfit2 }}</b></span><span>最大亏损 <b>{{ plan.maxLoss.toFixed(2) }} USDT</b></span></div><p v-if="plan.executionError" class="error">执行失败：{{ plan.executionError }}</p><div v-if="plan.status === 'pending'" class="actions"><button class="btn approve" @click="changeStatus(plan.id, 'approve')">批准</button><button class="btn reject" @click="changeStatus(plan.id, 'reject')">拒绝</button></div></article></div><p v-else class="muted empty">暂无交易计划。</p></section>
  </div>
</template>
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue'
import { useNotifyAPI } from '../composables/useNotifyAPI'
import type { TradePlan } from '../types'
const api = useNotifyAPI()
const plans = ref<TradePlan[]>([]), positions = ref<TradePlan[]>([]), snapshot = ref<any>({ available: false }), statusAvailable = ref(false), error = ref('')
let timer: number | undefined
async function refresh() { try { plans.value = await api.getTradePlans(); positions.value = await api.getTradingPositions(); const status: any = await api.getTradingStatus(); snapshot.value = await api.getTradingSnapshot(); statusAvailable.value = status.available === true; error.value = '' } catch (err) { error.value = err instanceof Error ? err.message : '加载失败' } }
async function changeStatus(id: string, status: 'approve' | 'reject') { try { await api.setTradePlanStatus(id, status); await refresh() } catch (err) { error.value = err instanceof Error ? err.message : '更新失败' } }
function statusLabel(status: TradePlan['status']): string { return ({ pending: '待审批', approved: '待执行', submitting: '提交中', open: '持仓中', closed: '已平仓', rejected: '已拒绝', expired: '已过期', submit_failed: '执行失败' })[status] }
function formatBalance(balance: any): string { const total = balance?.total?.USDT ?? balance?.free?.USDT; return total === undefined ? '--' : `${Number(total).toFixed(2)} USDT` }
function formatPercent(value?: number): string { return value === undefined ? '--' : `${(value * 100).toFixed(2)}%` }
onMounted(() => { refresh(); timer = window.setInterval(refresh, 15000) })
onUnmounted(() => { if (timer) window.clearInterval(timer) })
</script>
<style scoped>
.tab-content{display:flex;flex-direction:column;gap:20px}.chart-card{background:var(--bg-card);border:1px solid var(--border-color);border-radius:16px;padding:24px}.hero{display:flex;justify-content:space-between;align-items:center;background:linear-gradient(135deg,rgba(37,99,235,.16),rgba(15,23,42,.08))}.eyebrow{color:var(--accent-blue);font:700 .7rem 'Space Mono',monospace;letter-spacing:2px;margin:0 0 8px}h2,h3{margin:0;color:var(--text-primary)}h2{font-size:1.35rem}.muted{color:var(--text-secondary)}.status{font-size:.8rem;padding:8px 12px;border-radius:999px}.online{color:var(--accent-green);background:rgba(16,185,129,.12)}.offline{color:var(--accent-red);background:rgba(239,68,68,.12)}.dot{display:inline-block;width:7px;height:7px;border-radius:50%;background:currentColor;margin-right:6px}.chart-header{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px}.account-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.account-grid div{padding:12px;background:var(--bg-secondary);border-radius:8px}.account-grid span,.account-grid b{display:block}.account-grid span{font-size:.75rem;color:var(--text-secondary)}.account-grid b{margin-top:5px;color:var(--text-primary)}.positions,.plans{display:flex;flex-direction:column;gap:10px}.position,.plan{padding:16px;border:1px solid var(--border-color);border-left:3px solid var(--accent-green);border-radius:10px}.position.short,.plan.short{border-left-color:var(--accent-red)}.position-head,.plan-top{display:flex;align-items:center;gap:10px}.state{margin-left:auto;color:var(--text-secondary);font-size:.75rem}.long{color:var(--accent-green)}.short{color:var(--accent-red)}.metrics{display:flex;flex-wrap:wrap;gap:15px;margin-top:12px;color:var(--text-secondary);font-size:.8rem}.metrics b{color:var(--text-primary);font-family:'Space Mono',monospace}.profit{color:var(--accent-green)!important}.loss,.error{color:var(--accent-red)!important}.badge{font-size:.72rem;padding:3px 7px;border-radius:5px;background:var(--bg-secondary)}.btn{padding:8px 12px;border:1px solid var(--border-color);border-radius:7px;background:var(--bg-secondary);color:var(--text-primary);cursor:pointer}.approve{background:var(--accent-blue);color:#fff}.reject{color:var(--accent-red)}.actions{display:flex;gap:8px;margin-top:12px}.empty{padding:15px;text-align:center}@media(max-width:800px){.account-grid{grid-template-columns:1fr}.hero{align-items:flex-start;gap:12px;flex-direction:column}}
</style>
