<template>
  <div class="tab-content">
    <section class="chart-card hero"><div><p class="eyebrow">FUTURES / DRY-RUN</p><h2>交易计划控制台</h2><p class="muted">当前只生成模拟计划，不会发送真实订单。</p></div><div class="status" :class="statusAvailable ? 'online' : 'offline'"><span class="dot" />{{ statusAvailable ? 'Freqtrade 已连接' : 'Freqtrade 未连接' }}</div></section>
    <section class="chart-card"><div class="chart-header"><h3>模拟账户</h3><button class="btn" @click="refresh">刷新</button></div><div v-if="snapshot.available" class="account-grid"><div><span>余额</span><b>{{ formatBalance(snapshot.balance) }}</b></div><div><span>持仓数</span><b>{{ Array.isArray(snapshot.status) ? snapshot.status.length : 0 }}</b></div><div><span>模式</span><b>Futures / Isolated / Dry-run</b></div></div><p v-else class="muted">未连接到 Freqtrade dry-run（{{ snapshot.error || '等待服务' }}）</p></section>
    <section class="chart-card"><div class="chart-header"><h3>新建计划</h3><span class="risk-note">单笔风险上限 1% · 杠杆上限 2x</span></div><div class="form-grid"><label>交易对<input v-model="form.pair" /></label><label>方向<select v-model="form.side"><option value="long">做多</option><option value="short">做空</option></select></label><label>入场价<input v-model.number="form.entryPrice" type="number" step="any" /></label><label>止损价<input v-model.number="form.stopPrice" type="number" step="any" /></label><label>TP1<input v-model.number="form.takeProfit1" type="number" step="any" /></label><label>TP2<input v-model.number="form.takeProfit2" type="number" step="any" /></label><label>模拟权益<input v-model.number="form.equity" type="number" step="any" /></label><label>风险比例<input v-model.number="form.riskFraction" type="number" min="0.001" max="0.01" step="0.001" /></label></div><button class="btn primary" :disabled="saving" @click="submitPlan">{{ saving ? '计算中...' : '生成模拟计划' }}</button><p v-if="error" class="error">{{ error }}</p></section>
    <section class="chart-card"><div class="chart-header"><h3>计划队列</h3><button class="btn" @click="refresh">刷新</button></div><div v-if="plans.length" class="plans"><article v-for="plan in plans" :key="plan.id" class="plan" :class="plan.side"><div class="plan-top"><strong>{{ plan.pair }}</strong><span class="badge">{{ plan.side === 'long' ? '做多' : '做空' }}</span><span class="state">{{ statusLabel(plan.status) }}</span></div><div class="metrics"><span>入场 <b>{{ plan.entryPrice }}</b></span><span>止损 <b>{{ plan.stopPrice }}</b></span><span>TP1/TP2 <b>{{ plan.takeProfit1 }} / {{ plan.takeProfit2 }}</b></span><span>名义 <b>{{ plan.notional.toFixed(2) }} USDT</b></span><span>最大亏损 <b>{{ plan.maxLoss.toFixed(2) }} USDT</b></span></div><div v-if="plan.status === 'pending'" class="actions"><button class="btn approve" @click="changeStatus(plan.id, 'approve')">批准模拟执行</button><button class="btn reject" @click="changeStatus(plan.id, 'reject')">拒绝</button></div></article></div><p v-else class="muted empty">还没有交易计划。</p></section>
  </div>
</template>
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useNotifyAPI } from '../composables/useNotifyAPI'
import type { TradePlan } from '../types'
const { getTradePlans, createTradePlan, setTradePlanStatus, getTradingStatus, getTradingSnapshot } = useNotifyAPI()
const plans = ref<TradePlan[]>([]), saving = ref(false), error = ref(''), statusAvailable = ref(false), snapshot = ref<any>({ available: false })
const form = ref({ pair: 'BTC/USDT:USDT', side: 'long' as 'long' | 'short', entryPrice: 100, stopPrice: 98, takeProfit1: 102, takeProfit2: 104, equity: 10000, riskFraction: 0.005 })
async function refresh() { try { plans.value = await getTradePlans(); const status: any = await getTradingStatus(); snapshot.value = await getTradingSnapshot(); statusAvailable.value = status.available === true; error.value = '' } catch (err) { error.value = err instanceof Error ? err.message : '加载失败' } }
async function submitPlan() { saving.value = true; error.value = ''; try { await createTradePlan(form.value as any); await refresh() } catch (err) { error.value = err instanceof Error ? err.message : '创建失败' } finally { saving.value = false } }
async function changeStatus(id: string, status: 'approve' | 'reject') { try { await setTradePlanStatus(id, status); await refresh() } catch (err) { error.value = err instanceof Error ? err.message : '更新失败' } }
function statusLabel(status: TradePlan['status']): string { return ({ pending: '待审批', approved: '已批准（模拟）', rejected: '已拒绝', expired: '已过期' })[status] }
function formatBalance(balance: any): string { const total = balance?.total?.USDT ?? balance?.free?.USDT; return total === undefined ? '--' : `${Number(total).toFixed(2)} USDT` }
onMounted(refresh)
</script>
<style scoped>.tab-content{display:flex;flex-direction:column;gap:20px}.chart-card{background:var(--bg-card);border:1px solid var(--border-color);border-radius:16px;padding:24px}.hero{display:flex;justify-content:space-between;align-items:center;background:linear-gradient(135deg,rgba(37,99,235,.16),rgba(15,23,42,.08))}.eyebrow{color:var(--accent-blue);font:700 .7rem 'Space Mono',monospace;letter-spacing:2px;margin:0 0 8px}h2,h3{margin:0;color:var(--text-primary)}h2{font-size:1.35rem}.muted{color:var(--text-secondary)}.status{font-size:.8rem;padding:8px 12px;border-radius:999px}.online{color:var(--accent-green);background:rgba(16,185,129,.12)}.offline{color:var(--accent-red);background:rgba(239,68,68,.12)}.dot{display:inline-block;width:7px;height:7px;border-radius:50%;background:currentColor;margin-right:6px}.chart-header{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.risk-note{font-size:.75rem;color:var(--text-secondary)}.account-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.account-grid div{padding:12px;background:var(--bg-secondary);border-radius:8px}.account-grid span,.account-grid b{display:block}.account-grid span{font-size:.75rem;color:var(--text-secondary)}.account-grid b{margin-top:5px;color:var(--text-primary)}.form-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:18px}label{color:var(--text-secondary);font-size:.8rem}input,select{display:block;width:100%;box-sizing:border-box;margin-top:6px;padding:9px 10px;border:1px solid var(--border-color);border-radius:7px;background:var(--bg-secondary);color:var(--text-primary)}.btn{padding:8px 12px;border:1px solid var(--border-color);border-radius:7px;background:var(--bg-secondary);color:var(--text-primary);cursor:pointer}.btn:disabled{opacity:.5;cursor:wait}.primary,.approve{background:var(--accent-blue);border-color:var(--accent-blue);color:#fff}.reject{color:var(--accent-red)}.error{color:var(--accent-red)}.plans{display:flex;flex-direction:column;gap:12px}.plan{padding:16px;border:1px solid var(--border-color);border-left:3px solid var(--accent-green);border-radius:10px}.plan.short{border-left-color:var(--accent-red)}.plan-top{display:flex;align-items:center;gap:10px}.badge,.state{font-size:.72rem;padding:3px 7px;border-radius:5px;background:var(--bg-secondary)}.state{margin-left:auto;color:var(--text-secondary)}.metrics{display:flex;flex-wrap:wrap;gap:16px;margin:14px 0;color:var(--text-secondary);font-size:.8rem}.metrics b{color:var(--text-primary);font-family:'Space Mono',monospace}.actions{display:flex;gap:8px}.empty{text-align:center;padding:25px}@media(max-width:800px){.form-grid,.account-grid{grid-template-columns:repeat(2,1fr)}.hero{align-items:flex-start;gap:12px;flex-direction:column}}</style>
